### ISSUE TITLE
Missing textures from 1.10.2 and probably 1.11+

### ISSUE THREAD

**Issue by TexZeTech** [F0x06/OpenComputers-3D-Designer#3]
{0,13,0,16,16,16,texture="magma"}, 

works fine in game with OpenComputers-MC1.10.2-1.6.2.79-dev and most likely with the current release of OpenComputers-MC1.10.2-1.6.1.6

**Comment by F0x06** [comment]
Fixed in fc18761bd2e3cd73c7b9df6b80818a069fc5721f
