### ISSUE TITLE
How does one run this file

### ISSUE THREAD

**Issue by LittleTimmy52** [F0x06/OpenComputers-3D-Designer#5]
I installed it, but idk how to run/open/use it. im using win 10

**Comment by LittleTimmy52** [comment]
ok so i just run the html, but i get no visuals and in inspect element i get some errors

**Comment by F0x06** [comment]
Hi, you need to host it on a webserver, sometimes when running directly html files you can have issues, why not just use the live demo version ? https://f0x.me/OpenComputers-3D-Designer/

**Comment by LittleTimmy52** [comment]
I just wanted to see if u could do it myself, but I'll just use the web
version as it's easier
